# Indentation
indent_width: 2
continuation_indent_width: 2

# Enforce newlines
keep_simple_function_one_line: false
keep_simple_control_block_one_line: false

# Misc. style guides
extra_sep_at_table_end: true
single_quote_to_double_quote: true
