#!/usr/bin/env bash
set -euo pipefail

# Inherit systemd user environment
set -a
source <(/usr/lib/systemd/user-environment-generators/30-systemd-environment-d-generator)
set +a

# Use gnome-keyring as the ssh-agent
# eval "$(gnome-keyring-daemon --start)"
# export SSH_AUTH_SOCK
