[__config__]
keyfile = "~/.config/nvchecker/keyfile.toml"

[imv-wayland]
source = "github"
github = "eXeC64/imv"
use_latest_tag = true

[taplo-cli]
source = "cratesio"

[wlopm-git]
source = "git"
git = "https://git.sr.ht/~leon_plickat/wlopm"
use_commit = true

[yambar-wayland]
source = "git"
git = "https://codeberg.org/dnkl/yambar.git"
