[__config__]
keyfile = "~/.config/nvchecker/keyfile.toml"
oldver = "~/.local/state/nvchecker/oldver.json"
newver = "~/.local/state/nvchecker/newver.json"

[imv-wayland]
source = "github"
github = "eXeC64/imv"
use_latest_tag = true

[taplo-cli]
source = "cratesio"

[wlopm-git]
source = "git"
git = "https://git.sr.ht/~leon_plickat/wlopm"
use_commit = true

[yambar-wayland]
source = "git"
git = "https://codeberg.org/dnkl/yambar.git"

[arturo-bin]
source = "github"
github = "arturo-lang/arturo"
use_latest_release = true
