[__config__]
keyfile = "~/.config/nvchecker/keyfile.toml"
oldver = "~/.local/state/nvchecker/oldver.json"
newver = "~/.local/state/nvchecker/newver.json"

[arturo]
source = "github"
github = "arturo-lang/arturo"
use_latest_release = true

[cxbqn]
source = "github"
github = "ashermancinelli/cxbqn"
use_latest_tag = true

[imv]
source = "github"
github = "eXeC64/imv"
use_latest_tag = true

[taplo-cli]
source = "cratesio"

[wlopm]
source = "git"
git = "https://git.sr.ht/~leon_plickat/wlopm"
use_commit = true

[yambar]
source = "git"
git = "https://codeberg.org/dnkl/yambar.git"
