#!/bin/sh

# See the river(1), riverctl(1), and rivertile(1) man pages for complete
# documentation.

# winkey = Mod4; basic conf
mod='Mod4'
alt='Mod1'
riverctl map normal $mod Q close
riverctl map normal $mod+Shift E exit

# terminal
riverctl map normal $mod Return spawn foot

# launcher
riverctl map normal $mod+Shift Return spawn 'nwg-drawer -ovl -term xterm'

# power menu
riverctl map normal $mod Escape spawn 'nwg-bar'

# view focus
riverctl map normal $mod Z zoom
riverctl map normal $mod J focus-view next
riverctl map normal $mod K focus-view previous

# swap focus
riverctl map normal $mod+Shift J swap next
riverctl map normal $mod+Shift K swap previous

# rivertile main factor/count
riverctl map normal $mod H mod-layout-value rivertile fixed main_factor -0.05
riverctl map normal $mod L mod-layout-value rivertile fixed main_factor +0.05
riverctl map normal $mod+Shift H mod-layout-value rivertile int main_count +1
riverctl map normal $mod+Shift L mod-layout-value rivertile int main_count -1

# move/resize
riverctl map normal "${mod}+${alt}" H move left 100
riverctl map normal "${mod}+${alt}" J move down 100
riverctl map normal "${mod}+${alt}" K move up 100
riverctl map normal "${mod}+${alt}" L move right 100
riverctl map normal "${mod}+${alt}+Control" H snap left
riverctl map normal "${mod}+${alt}+Control" J snap down
riverctl map normal "${mod}+${alt}+Control" K snap up
riverctl map normal "${mod}+${alt}+Control" L snap right
riverctl map normal "${mod}+${alt}+Shift" H resize horizontal -100
riverctl map normal "${mod}+${alt}+Shift" J resize vertical 100
riverctl map normal "${mod}+${alt}+Shift" K resize vertical -100
riverctl map normal "${mod}+${alt}+Shift" L resize horizontal 100
riverctl map-pointer normal $mod BTN_LEFT move-view
riverctl map-pointer normal $mod BTN_RIGHT resize-view
riverctl map normal $mod+Shift Z toggle-float

# main view location
riverctl map normal $mod Up set-layout-value rivertile string main_location top
riverctl map normal $mod Right set-layout-value rivertile string main_location right
riverctl map normal $mod Down set-layout-value rivertile string main_location bottom
riverctl map normal $mod Left set-layout-value rivertile string main_location left

for i in $(seq 1 9); do
  tags=$((1 << (i - 1)))
  riverctl map normal $mod "$i" set-focused-tags $tags
  riverctl map normal $mod+Shift "$i" set-view-tags $tags
  riverctl map normal $mod+Control "$i" toggle-focused-tags $tags
  riverctl map normal $mod+Shift+Control "$i" toggle-view-tags $tags
done
tags1to9=$(((1 << 9) - 1))
riverctl map normal $mod 0 set-focused-tags "$tags1to9"
riverctl map normal $mod+Shift 0 set-view-tags "$tags1to9"

# passthrough mode for nested wayland compositors
riverctl declare-mode passthrough
riverctl map normal $mod F11 enter-mode passthrough
riverctl map passthrough $mod F11 enter-mode normal

# Various media key mapping examples for both normal and locked mode which do
# not have a modifier
for mode in normal locked; do
  # Eject the optical drive
  riverctl map $mode None XF86Eject spawn 'eject -T'

  # Control pulse audio volume with amixer
  riverctl map $mode None XF86AudioRaiseVolume spawn 'pamixer -i 5'
  riverctl map $mode None XF86AudioLowerVolume spawn 'pamixer -d 5'
  riverctl map $mode None XF86AudioMute spawn 'pamixer -t'

  # Control MPRIS aware media players with playerctl (https://github.com/altdesktop/playerctl)
  riverctl map $mode None XF86AudioMedia spawn 'playerctl play-pause'
  riverctl map $mode None XF86AudioPlay spawn 'playerctl play-pause'
  riverctl map $mode None XF86AudioPrev spawn 'playerctl previous'
  riverctl map $mode None XF86AudioNext spawn 'playerctl next'

  # Control screen backlight brighness with light (https://github.com/haikarainen/light)
  riverctl map $mode None XF86MonBrightnessUp spawn 'light -A 5'
  riverctl map $mode None XF86MonBrightnessDown spawn 'light -U 5'
done

# Change border colors
riverctl border-color-focused '0x9ece6a'
riverctl border-color-unfocused '0x24283b'
riverctl border-width 2

# Set repeat rate
riverctl set-repeat 50 300

# float app-ids
riverctl float-filter-add app_id 'float'
riverctl float-filter-add app_id 'popup'
riverctl float-filter-add app-id 'anki'
riverctl float-filter-add title 'Sharing Indicator'

# Set default cursor theme
riverctl xcursor-theme capitaine-cursors 24

# program autostart
riverctl spawn "swaybg -m fill -i ${HOME}/media/pics/current_wall"
riverctl spawn 'mako'
riverctl spawn 'yambar'
riverctl spawn 'dex -a'
riverctl spawn 'swayidle -w'
riverctl spawn '/usr/lib/xdg-desktop-portal-gtk'
riverctl spawn 'dbus-update-activation-environment --systemd DISPLAY MOZ_DBUS_REMOTE'

# Set and exec into the default layout generator, rivertile.
# River will send the process group of the init executable SIGTERM on exit.
riverctl default-layout rivertile
exec rivertile
