#!/usr/bin/env bash

# See the river(1), riverctl(1), and rivertile(1) man pages for complete
# documentation.

# winkey = Mod4; basic conf
mod='Mod4'
alt='Mod1'
riverctl map normal $mod Q close
riverctl map normal $mod+Shift E exit

# start program on keypress
riverctl map normal $mod Return spawn 'foot'             # terminal
riverctl map normal $mod+Shift Return spawn 'bemenu-run' # launcher
riverctl map normal $mod period spawn 'bemoji -t'        # emoji
riverctl map normal None Print spawn 'iriver'            # printscreen

# view focus
riverctl map normal $mod Z zoom
riverctl map normal $mod J focus-view next
riverctl map normal $mod K focus-view previous

# swap focus
riverctl map normal $mod+Shift J swap next
riverctl map normal $mod+Shift K swap previous

# rivertile main factor/count
riverctl map normal $mod H mod-layout-value rivertile fixed main_factor -0.05
riverctl map normal $mod L mod-layout-value rivertile fixed main_factor +0.05
riverctl map normal $mod+Shift H mod-layout-value rivertile int main_count +1
riverctl map normal $mod+Shift L mod-layout-value rivertile int main_count -1

# move/resize
riverctl map normal "${mod}+${alt}" H move left 100
riverctl map normal "${mod}+${alt}" J move down 100
riverctl map normal "${mod}+${alt}" K move up 100
riverctl map normal "${mod}+${alt}" L move right 100
riverctl map normal "${mod}+${alt}+Control" H snap left
riverctl map normal "${mod}+${alt}+Control" J snap down
riverctl map normal "${mod}+${alt}+Control" K snap up
riverctl map normal "${mod}+${alt}+Control" L snap right
riverctl map normal "${mod}+${alt}+Shift" H resize horizontal -100
riverctl map normal "${mod}+${alt}+Shift" J resize vertical 100
riverctl map normal "${mod}+${alt}+Shift" K resize vertical -100
riverctl map normal "${mod}+${alt}+Shift" L resize horizontal 100
riverctl map-pointer normal $mod BTN_LEFT move-view
riverctl map-pointer normal $mod BTN_RIGHT resize-view
riverctl map normal $mod+Shift Z toggle-float

# main view location
riverctl map normal $mod Up set-layout-value rivertile string main_location top
riverctl map normal $mod Right set-layout-value rivertile string main_location right
riverctl map normal $mod Down set-layout-value rivertile string main_location bottom
riverctl map normal $mod Left set-layout-value rivertile string main_location left

for i in $(seq 1 9); do
  tags=$((1 << (i - 1)))
  riverctl map normal $mod "$i" set-focused-tags $tags
  riverctl map normal $mod+Shift "$i" set-view-tags $tags
  riverctl map normal $mod+Control "$i" toggle-focused-tags $tags
  riverctl map normal $mod+Shift+Control "$i" toggle-view-tags $tags
done
tags1to9=$(((1 << 9) - 1))
riverctl map normal $mod 0 set-focused-tags "$tags1to9"
riverctl map normal $mod+Shift 0 set-view-tags "$tags1to9"

# passthrough mode for nested wayland compositors
riverctl declare-mode passthrough
riverctl map normal $mod F11 enter-mode passthrough
riverctl map passthrough $mod F11 enter-mode normal

# Various media key mapping examples for both normal and locked mode which do
# not have a modifier
for mode in normal locked; do
  # Eject the optical drive
  riverctl map $mode None XF86Eject spawn 'eject -T'

  # Control pulse audio volume with amixer
  riverctl map $mode None XF86AudioRaiseVolume spawn 'pamixer -i 5'
  riverctl map $mode None XF86AudioLowerVolume spawn 'pamixer -d 5'
  riverctl map $mode None XF86AudioMute spawn 'pamixer -t'

  # Control MPRIS aware media players with playerctl (https://github.com/altdesktop/playerctl)
  riverctl map $mode None XF86AudioMedia spawn 'playerctl play-pause'
  riverctl map $mode None XF86AudioPlay spawn 'playerctl play-pause'
  riverctl map $mode None XF86AudioPrev spawn 'playerctl previous'
  riverctl map $mode None XF86AudioNext spawn 'playerctl next'

  # Control screen backlight brighness with brightnessctl
  riverctl map $mode None XF86MonBrightnessUp spawn 'brightnessctl set +5'
  riverctl map $mode None XF86MonBrightnessDown spawn 'brightnessctl set 5-'
done

# Change border colors
riverctl border-color-focused '0x76946a'
riverctl border-color-unfocused '0x090618'
riverctl border-width 2

# Set repeat rate
riverctl set-repeat 50 300

# float app-ids
riverctl float-filter-add app-id 'float'
riverctl float-filter-add app-id 'popup'
riverctl float-filter-add app-id 'anki'
riverctl float-filter-add title 'Sharing Indicator'

# Set default cursor theme
riverctl xcursor-theme capitaine-cursors-light 24

# Input configuration
riverctl input 1133:49284:Logitech_G203_Prodigy_Gaming_Mouse accel-profile flat
riverctl input 1133:49284:Logitech_G203_Prodigy_Gaming_Mouse pointer-accel 0.3

# program autostart
riverctl spawn 'wpaperd'
riverctl spawn 'mako'
riverctl spawn 'yambar'

# Read from ~/.config/autostart/*.desktop files
riverctl spawn 'autostart'

# Fix slow-to-open GTK programs
riverctl spawn 'dbus-update-activation-environment --systemd DISPLAY WAYLAND_DISPLAY SWAYSOCK'

# Set and exec into the default layout generator, rivertile.
# River will send the process group of the init executable SIGTERM on exit.
riverctl default-layout stacktile
exec stacktile
